# Generated by Django 5.2.7 on 2025-11-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введіть назву книги', max_length=255, verbose_name='Назва книги')),
                ('author', models.CharField(help_text="Введіть ім'я автора книги", max_length=255, verbose_name='Автор')),
                ('genre', models.CharField(help_text='Введіть жанр книги (наприклад, фантастика, детектив)', max_length=100, verbose_name='Жанр')),
                ('publication_year', models.PositiveIntegerField(help_text='Введіть рік видання книги', verbose_name='Рік видання')),
                ('user_id', models.IntegerField(help_text='ID користувача з Auth Service', verbose_name='ID користувача')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id'], name='books_book_user_id_dff089_idx'), models.Index(fields=['author'], name='books_book_author_b941fe_idx'), models.Index(fields=['genre'], name='books_book_genre_4a7cdf_idx')],
            },
        ),
    ]
